import { readFile, writeFile, appendFile } from 'fs/promises'

const invoke = async (action, path, data = null) => {
    switch (action) {
        case 'read':
            const output = await readFile(path, 'utf-8')
            console.log(output);
            break;
        case 'write':
            console.log(await writeFile(path, data));
            break;
        case 'append':
            await appendFile(path, data);
            break;
    }
}

export const a = 10;
export const b = 10;
export default invoke

// readFile('./package.jsn', 'utf-8').then((res) => {
//     console.log(res);
// }).catch((err) => {
//     console.log(err);
// })

// invoke('read', './some-text.txt')
// invoke('write', './some-text.txt', 'This file was generated by writeFile function');
invoke('append', './some-text.txt', 'line 2: i am new line')